### ISSUE TITLE
Add default lifecycle policies to all S3 buckets in Dev/Test env

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#106]
### 💡 Description

In the dev and test environment, we should not keep data out in S3 for more than a week or 2.

**Comment by viviant100** [comment]
DSIO-6042 is created to track work.

**Comment by viviant100** [comment]
DSIO-6042 is in progress

**Comment by tloubrieu-jpl** [comment]
After 2 weeks without update objects will be deleted.
