### ISSUE TITLE
Create test/prod SBN archive buckets

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#107]
### 💡 Description

In order to effectively test https://github.com/NASA-PDS/s3-browser-cloudfront/issues/31, we need a representative product archive bucket for SBN. Let's create that based upon the naming scheme discussed on slack.

* pds-sbn-archive-dev
* pds-sbn-archive-test
* pds-sbn-archive-prod

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo will write the documentation so that the SA's can eventually deploy in production themselves.

**Comment by viviant100** [comment]
SBN archive buckets are created in the 3 environments below:
- (1) DEV
   -  `pds-sbn-archive-cold-mcp-dev` (us-east-2)
   -  `pds-sbn-archive-hot-mcp-dev` (us-west-2)
- (2) TEST
    - `pds-sbn-archive-test` (us-west-2)   
- (3) PROD
      - `pds-sbn-archive-prod` (us-west-2)

**Comment by jordanpadams** [comment]
Archive bucket is created. Needs to be hooked up to Nucleus per production deployment for Nucleus.

Need new Nucleus ticket for prod deployment for SBN
