### ISSUE TITLE
[SECURITY] Ensure CloudFront distributions have logging enabled-PDS

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/planetary-data-cloud#108]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the vulnerability

Per MCP ticket (GSD-3259), due date is 6/1/24 to enable logging on both dev and test env:

AWS suggests the following remediation step(s). (See [remediation instructions](https://docs.aws.amazon.com/securityhub/latest/userguide/cloudfront-controls.html#cloudfront-5))

To configure access logging for a CloudFront distribution, see [Configuring and using standard logs (access logs)](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html) in the Amazon CloudFront Developer Guide.

We ask that you initiate and complete remediation the non-compliant resources within 30 days of this notice. We understand that this may require technical planning and that you may require additional time beyond our projected timeline. If so, please coordinate herein regarding an exemption from our process and a proposed timeline.

### 🕵️ Expected behavior

I expected [...]

### 📜 To Reproduce

```bash
1.
2.
3.
...
```

### 🖥 Environment Info

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

### 🦄 Related requirements

🦄 #xyz

**Comment by tloubrieu-jpl** [comment]
Ready for review by the SA's , @eddiesarevalo and @viviant100 will present them the feature at a meeting.

**Comment by tloubrieu-jpl** [comment]
@viviant100 is reviewing the logging with MCP.

**Comment by viviant100** [comment]
reviewed and the compilance status went from failed to pass.  Waiting for Gabe's confirmation before we apply the changes to other cloudfront instances in dev and test environment.

**Comment by tloubrieu-jpl** [comment]
The same configuration has been applied to all deployments in dev.
Next the configuration will be deployed in test by @viviant100 or the SAs.

**Comment by viviant100** [comment]
I verified that the logging fix passed the Security Hub check in the dev venue.
