### ISSUE TITLE
Come up with an approach to keep track of AWS costs for each PDS Node 

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/planetary-data-cloud#110]
### 💡 Description

At the moment, we have many AWS components / services of Nucleus deployed in a single AWS account. The services such as MWAA are shared between PDS Nodes to reduce costs. However, as a result we do not see billing reports for each PDS Node. It is required to come up with an approach to keep track of AWS costs for each PDS Node.

**Comment by ramesh-maddegoda** [comment]
I got a response for the case ID 172204012900929, that I created with AWS. They said "
Please note that after you create and apply user-defined tags to your resources, it can take up to 24 hours for the tag keys to appear on your cost allocation tags page for activation. It can then take up to 24 hours for tag keys to activate. This duration may have caused a delay in the tag appearing. We'd therefore request your patience while it gets updated.".
 
Now I can see the tag pds_node and get the cost and usage by tag value.

**Comment by ramesh-maddegoda** [comment]
Based on the above comments and experiments, we can use cost allocation tags to find out cost for each PDS Node.

- It is required to add pds_node to every AWS resource (can use Terraform for that) 
- Then it is possible to use the cost explorer to get cost by each tag
- Use Dimension and Tag drop down lists to filter costs

**Comment by tloubrieu-jpl** [comment]
@viviant100 @jordanpadams can you review the solution proposed Ramesh.

**Comment by jordanpadams** [comment]
@ramesh-maddegoda @tloubrieu-jpl sounds good to me.

**Comment by jordanpadams** [comment]
@viviant100 can you work with @ramesh-maddegoda and document how we plan to tag and track these costs? It can be very basic right now.
