### ISSUE TITLE
Improve the Cognito service in production, as a PDS SSO

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/planetary-data-cloud#111]
### 💡 Description

- [x] the invitation message should be updated so that it is not only for DUM but for the PDS Engineering node tools (including registry for examle).
- [x] the invitation message should contain a link to update the password
- [x] the link to update the password should forward to a valid URL (PDS Web Site, specific welcome web page ?)

**Comment by tloubrieu-jpl** [comment]
Ramesh is updating the terraform, in the DUM repository.

**Comment by ramesh-maddegoda** [comment]
Created a pull request https://github.com/NASA-PDS/pds-mcp-infra/pull/10

**Comment by tloubrieu-jpl** [comment]
Everything is configured in the terraform script which needs to be run twice.

**Comment by nutjob4life** [comment]
Cognito is the recommended approach vs using AWS accounts for people outside JPL

Load balancer rules need to be troubleshooted

Redirection to Airflow UI isn't working; attempting fix (going to some Cognito URL) Small gap!

**Comment by jordanpadams** [comment]
PR in review

**Comment by ramesh-maddegoda** [comment]
PR approved and code merged
