### ISSUE TITLE
Refine Data Backup, Disaster Recovery and Configuration Management Plans

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#112]
### 💡 Description

Per Nucleus update to push data to Glacier in new region, we need to document our new data backup plan for PDS archive data, including glacier in new region, S3 with versioning enabled, and rationale for the decision we are making.

An of rationale are S3 provides 3+ copies of the data, all in different availability zones (AZs) (link needed) within a given region, which provides 99.999999999% (eleven 9’s) of durability. However, all those AZs are within 60 miles of each other (https://aws.amazon.com/s3/faqs/). In the event of a catastrophic event, there is a possibility of data loss. Other rationale regarding PDS Policy and other alternatives that we chose not to pursue.

Tightly coupled to #75 

### 🧒 Child tasks

* https://github.com/NASA-PDS/planetary-data-cloud/issues/116
* https://github.com/NASA-PDS/planetary-data-cloud/issues/113

**Comment by jordanpadams** [comment]
closes #75

**Comment by jordanpadams** [comment]
Standup status: Blocked waiting for review from @jordanpadams

**Comment by jordanpadams** [comment]
📆 11/2024 status: Presented at MC F2F. @viviant100 to move content to wiki. In work. On schedule

**Comment by viviant100** [comment]
Both plan and presentation are in wiki. This ticket can be closed.
