### ISSUE TITLE
CATCH: Gather requirements and AWS architecture needs

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#120]
### 💡 Description

Gather requirements and design needs for CATCH tool from SBN

**Comment by viviant100** [comment]
current CATCH requirements and design are captured in the wiki "Cloud Migration (Services and Tools)" section.

**Comment by jordanpadams** [comment]
We can call this done based upon our initial kickoff meeting with SBN on 11/8
