### ISSUE TITLE
Phase 1: PDS-EN to provide terraform templates for SBN to capture the current status of CATCH.

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/planetary-data-cloud#122]
- [ ] EC2
- [ ] RDS

**Comment by viviant100** [comment]
- The EC2 Terraform module was sent as a ZIP file because the infra repo is private.
- RDS (specifically postgres) terraform module was provided via https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster.html with example below:
`resource `"aws_rds_cluster" "postgresql\" {

      cluster_identifier      = "aurora-cluster-demo"
      engine                  = "aurora-postgresql"
      availability_zones      = ["us-west-2a", "us-west-2b", "us-west-2c"]
      database_name           = "mydb"
      master_username         = "foo"
      master_password         = "must_be_eight_characters"
      backup_retention_period = 5
      preferred_backup_window = "07:00-09:00"
}`

**Comment by jordanpadams** [comment]
Terraform scripts were distributed to SBN. Will iterate with them to provide additional support as needed.
