### ISSUE TITLE
Phase 1: PDS-EN to provide cloud endpoint for SBN to integrate the endpoint into SBN Survey Image Service.

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/planetary-data-cloud#123]
The SBN Survey Image Service currently uses the SBN-PSI S3 bucket to display images. PDS-EN will provide a cloud endpoint containing CSS data, enabling SBN to start using PDS-EN's CSS data in the cloud.

**Comment by viviant100** [comment]
Provided 2 ways to access css cloud - both got access denied.  Need review with both dev and SA team to get permission reverted and set correctly again.

- (1) https://pds-uat.mcp.nasa.gov/data/open-data-registry/   (AccessDenied Error)
- (2) aws s3 ls --no-sign-request s3://pds-css-archive/           (AccessDenied Error)

**Comment by jordanpadams** [comment]
S3 is now publicly accessible

**Comment by jordanpadams** [comment]
Nevermind. This is not working again...

**Comment by viviant100** [comment]
this is complete and can be closed.
