### ISSUE TITLE
CSS ODR bucket no longer accessible to the public

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#125]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

```
$ aws s3 ls --no-sign-request s3://pds-css-archive/
```
doesn't work

### 🕵️ Expected behavior

I expected the data to be accessible

### 📜 To Reproduce

```
$  aws s3 ls --no-sign-request s3://pds-css-archive/

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by tloubrieu-jpl** [comment]
The ODR bucket is still not open.

**Comment by jordanpadams** [comment]
As of 11/12/24 at 0137pm Pacific, this works:

```
$ aws s3 ls --no-sign-request s3://pds-css-archive/
                           PRE sbn/
```

But per our SA team, this was changed earlier and then reverted

**Comment by jordanpadams** [comment]
This appears to have been fixed. DSIO ticket and GSD ticket created and closed out.
