### ISSUE TITLE
document the AWS infrastructure used by PDS

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/planetary-data-cloud#36]
## 💪 Motivation
...so to understand the hosts/services used by the deployed software https://wiki.jpl.nasa.gov/display/PDSEN/Software+Installation+and+Deployment+Guides

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
this AWS infra is being documented on the wiki
