### ISSUE TITLE
Develop AWS architecture for "lift-and-shift" of SBN-PSI + EN Tools pipeline

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#48]

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda is blocked with something on NGAP

**Comment by tloubrieu-jpl** [comment]
For this build B13.1,  the SBN-PDS pipeline will stay on-prem

**Comment by jordanpadams** [comment]
Descoping from B13.1 per architecture discusses with SBN-PSI

**Comment by jordanpadams** [comment]
closing this as wontfix since we will do this piecemeal, not one big migration of tools
