### ISSUE TITLE
Design and Implement Minor Planet Center (MPC) Cloud Backup Solution

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#69]
## 💡 Description

* Requirements: [MPCPGDBrequirements230823.pdf](https://github.com/NASA-PDS/planetary-data-cloud/files/13605303/MPCPGDBrequirements230823.pdf)

**Comment by tloubrieu-jpl** [comment]
Postgresql database needs to have hot backup or be replicated in a different geographical location.

**Comment by tloubrieu-jpl** [comment]
@anilnatha says the database will need to be encrypted if hosted on AWS/JPL. Might be needed as well on MCP.

@sjoshi-jpl and @ramesh-maddegoda will discuss a solution for the request of SBN.

**Comment by jordanpadams** [comment]
📆 November status: Initial requirement identified and discussions with SBN have begun. Initial design roundtable planned for this sprint.

**Comment by jordanpadams** [comment]
📆 December status: Initial design discussed with SBN. On schedule.

**Comment by jordanpadams** [comment]
📆 01/2024 status: Design ongoing. Completion date delayed 1 sprint, but this work is being done by SBN. No impact on delivery.

**Comment by jordanpadams** [comment]
📆 02/2024 status: Design complete. Assisting customer, as needed, with debugging issues in AWS
