### ISSUE TITLE
Update cost model to provide more accurate representation of existing Registry deployments

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#72]
## 💡 Description

We have been doing numerous tuning activities of the node registries over the past several months. Let's make sure our cost model accommodates that. If we only have 1 memory allocation to use as a multiplier in the model, use the worst case (e.g. 200GB)

**Comment by jordanpadams** [comment]
Status: @sjoshi-jpl updating the cost models

**Comment by tloubrieu-jpl** [comment]
Hi @sjoshi-jpl, @viviant100, @jordanpadams , what is the status of this ticket ? I am not finding the related document ? Although it is private of course we need a way to retrieve it.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl Go to our internal Google Workspace, and search for "PDS Cost Model - Overall"
