### ISSUE TITLE
As a user, I want a warm backup of my archive data to be available in the event of corruption of of primary archive data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#75]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Archivist

### 💪 Motivation

...so that I can ensure there is another copy of the data somewhere I can get.

### 📖 Additional Details

Per [this PDS policy](https://pds.nasa.gov/datastandards/documents/policy/data_delivery_backup_051007.pdf), all PDS archive data must have 3 copies:
* 1 online (hot)
* 1 off-line, ready in case of disaster or data corruption/user error (warm)
* 1 copy at NSSDCA (cold)

We need to design, document, and implement how we accomplish this requirement in MCP.

Some questions/comments?
* Research what ESDIS does?
* AWS Deep Archive or Glacier?
* Do we need to store in another region?
* How do we handle the interim state when we are waiting for NSSDCA to download the data?

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by viviant100** [comment]
Initial design in lucid "Archive of Data Flow System Diagram (2023-11)" and internal wiki "Data Backup Plan".

**Comment by viviant100** [comment]
Design update to include ODR as 1st copy of hot backup for Nucleus.  Went over design with @ramesh-maddegoda, and ready to be implemented when ODR s3 bucket is set up.

**Comment by viviant100** [comment]
- (1) STAGING bucket: ODR s3 bucket (`pds-css-archive`) has been set up to sync with MCP prod s3 bucket (`pds-prod-nucleus-staging`)
- (2) ARCHIVE bucket: DEV s3 bucket (`pds-sbn-archive-hot-mcp-dev`) has been set up to sync with MCP dev bucket(`pds-sbn-archive-cold-mcp-dev`)
- (3) The same archive strategy needs to be applied in MCP PROD by the SA.
- (4) A formal document for the Data Backup and Disaster Recovery Plan has been created and will be under review.

**Comment by jordanpadams** [comment]
Closing this for now. Next iteration of document to occur in B15.1

**Comment by jordanpadams** [comment]
[Data Backup and Disaster Recovery Plan for PDS Archive Data.20240929.docx](https://github.com/user-attachments/files/17479417/Data.Backup.and.Disaster.Recovery.Plan.for.PDS.Archive.Data.20240929.docx)

**Comment by c-suh** [comment]
i&t.skip added because the document above satisfies this issue.
