### ISSUE TITLE
Develop PDC Tenant Roles

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#80]
## 💡 Description

See comments here for more details on discussions offline: https://github.com/NASA-PDS/monitoring/issues/15#issuecomment-2183109413

**Comment by jordanpadams** [comment]
📆 05/2024 status: In work. On schedule

**Comment by viviant100** [comment]
Submitted a request to create a sub-project under the “PDS-Management” project (GSD-3636)

**Comment by tloubrieu-jpl** [comment]
Next we need to see how nucleus can handle that.

**Comment by jordanpadams** [comment]
📆 06/2024 status: Working on getting these roles to work with Nucleus across accounts. On schedule.

**Comment by jordanpadams** [comment]
📆 07/2024 status: Roles created and model started. Need to continue to operationalize this. No impact on other tasks or customers.

**Comment by jordanpadams** [comment]
@viviant100 where are we at with this?

**Comment by jordanpadams** [comment]
📆 08/2024 status: In work. On schedule for completion by end of sprint.

**Comment by tloubrieu-jpl** [comment]
IMG and SBN roles are being created by MCP.

**Comment by viviant100** [comment]
The PDS-Management Kion project has been renamed to "PDS Core Data Services" with 1 single read-only role.

**Comment by jordanpadams** [comment]
@viviant100 just confirming before we close this out:

> (1) The PDS-Management Kion project has been renamed to "PDS Core Data Services" with 1 single read-only role.

When you say "1 single read-only role", this is really 1 single read-only **tenant role**? In other words, our existing DevOps/SysAdmin roles at our top-level project still all work there.

**Comment by viviant100** [comment]
Confirmed, our existing DevOps/SysAdmin roles still works with PDS-OU.  
It's the "PDS Core Data Services" project that only has "read-only" account.

**Comment by jordanpadams** [comment]
Roles done for SBN, which we will consider done for this task
