### ISSUE TITLE
Migrate PDS EC2 instances from JPL AWS to MCP

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/planetary-data-cloud#81]
## 💡 Description

Move all PDS EC2 instances from JPL AWS to MCP. Following are the required steps:

Steps: https://repost.aws/knowledge-center/share-ebs-volume#

Migrate hosts in this order:

pdscloud-engineering-ol8
pdscloud-prod1-ol8
pdscloud-prod2-ol8
pdscloud-gamma-ol8

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl is woring on the migration of data from JPL AWS to MCP.

**Comment by tloubrieu-jpl** [comment]
@c-suh and @rchenatjpl validated the migration done by sync.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl investigates the latest updates.

**Comment by tloubrieu-jpl** [comment]
This ticket is completed but we need another ticket to handle the disk space (EFS) across AWS accounts, especially between OPS and Staging.

**Comment by jordanpadams** [comment]
Closing for more better #85

**Comment by jordanpadams** [comment]
@sjoshi-jpl @tloubrieu-jpl as a reminder, let's try to avoid putting the EC2 names in these tickets. per request from the SA team, we should not put those in here.
