### ISSUE TITLE
Set Up Aria Share For Archive Browsing

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/planetary-data-cloud#82]
Setting up aria share to browse our bucket. 

Need to set up our s3 bucket and cloud front in the same way as Susan's example.

Need to locate original aria share code. Susan will ask for it.

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl I was able to set up a bucket with the same settings as the aria-share example "pds-infrastructure-temp". I added the contents from our "pds-messenger-data-copy" and it now allows us to browse the directories: https://d15o8c96j0o8g0.cloudfront.net/

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo wrote the documentation which will go to the internal wiki.
