### ISSUE TITLE
Change Aria Share Header Footer

### ISSUE THREAD

**Issue by eddiesarevalo** [NASA-PDS/planetary-data-cloud#84]
### 💡 Description

Change the header footer for our copy of aria share. 

Use the look and feel that PDS imaging is using.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo will re-use the header that @c-suh made before.
He will contact @anilnatha and @tariqksoliman for the footer.

**Comment by jordanpadams** [comment]
Status: Able to add header to page. In the middle of adding footer.

**Comment by eddiesarevalo** [comment]
Header footer added in https://github.com/NASA-PDS/s3-directory-listing/commit/9f9059512d144889baaacca1ed986803c8cff446

**Comment by jordanpadams** [comment]
Closed per commit above
