### ISSUE TITLE
Separate Ops vs Dev EFS data and EC2 instances in MCP

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/planetary-data-cloud#85]
### 💡 Description

1. Separate Dev vs Ops EFS data in Dev MPC
2. Create new EFS with Ops data in Ops / Prod accounts 
3. Create Ops / Prod instances in respective accounts and mount EFS

### ⚔️ Parent Epic / Related Tickets

refs #81

**Comment by sjoshi-jpl** [comment]
@jordanpadams @tloubrieu-jpl @viviant100 who can I work with to determine which data is dev vs ops in the EFS? Is there someone from operations Richard or Catherine who can assist?

**Comment by viviant100** [comment]
@sjoshi-jpl I just invited you to the operation team tomorrow and we can discuss there.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl created a ticket to create a VPC to share the EFS volume.

**Comment by nutjob4life** [comment]
SA team has "unblocked" this and Sagar is testing mounting instances from dev to ops account and is optimistic will be moving forward and have a migration plan to move to JPL AWS.

One other to-do: figure out instances in dev and test account only have read access to EFS, not write access. Gotta figure this out!

**Comment by jordanpadams** [comment]
@sjoshi-jpl any status on this? Are we good to close out?

**Comment by tloubrieu-jpl** [comment]
Still need to delete the dev MCP EFS space. There is a SA ticket.

**Comment by sjoshi-jpl** [comment]
SA team has confirmed this is completed and can be closed.
