### ISSUE TITLE
Cleanup NGAP resources

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#88]
### 💡 Description

Since we have moved over to MCP for dev, test, and prod, let's inventory and cleanup any resources we are using in NGAP.

**Comment by jordanpadams** [comment]
Status: In work by @ramesh-maddegoda . Cleaning up some Cumulus components that were deployed per Terraform.

**Comment by sjoshi-jpl** [comment]
@jordanpadams I went into NGAP and delete most of what I had created for registry. What's left is all nucleus and airflow. @ramesh-maddegoda  you might want to take a look at those resources and delete them as needed.

**Comment by ramesh-maddegoda** [comment]
@jordanpadams , @sjoshi-jpl , in fact there are still lots of resources created by previous cumulus deployments. Some of those resources are failed to remove due to dependencies.

**Comment by tloubrieu-jpl** [comment]
@ramesh-maddegoda is reviewing the remaining component starting from the most expensive.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl cleaned the registry related resources.

**Comment by ramesh-maddegoda** [comment]
Cleaned-up all NGAP Resources created by PDS (except 2 Cogntio pools) and shared the status with the team.

**Comment by tloubrieu-jpl** [comment]
We keep a few remaining resources from NGAP (system monitoring) and cognito which costs are not significant.
