### ISSUE TITLE
As a user, I want to know how the CSS archive is organized and how users can find the data they need

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#90]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data User

### 💪 Motivation

...so that I can know how to find and use the data, and apply to AWS Open Data Registry

### 📖 Additional Details

See Step 2 from https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf

### Acceptance Criteria

**Given** the CSS archive
**When I perform** the steps described in the newly generated documentation
**Then I expect** to understand how the data archive is organized

**Given** the CSS archive
**When I perform** the steps described in the newly generated documentation
**Then I expect** to understand how to find a specific subset of data that I need

**Comment by viviant100** [comment]
CSS data structure is documented in https://sbnarchive.psi.edu/pds4/surveys/gbo.ast.catalina.survey/document/CSS_bundle_overview_v12.pdf (section 2 -  Catalina Sky Survey Archive Bundle Structure).

**Comment by tloubrieu-jpl** [comment]
Hi @jordanpadams , during the standup we were wondering if we want a specific documentation for CSS here or a generic service for any archive on the cloud to be discovered by the users.

**Comment by gxtchen** [comment]
@tloubrieu-jpl where is our document that contains the information in https://sbnarchive.psi.edu/pds4/surveys/gbo.ast.catalina.survey/document/CSS_bundle_overview_v12.pdf?
