### ISSUE TITLE
As a user, I want to know how to use CSS data on AWS

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#91]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data user

### 💪 Motivation

...so that I can perform analysis alongside the data in AWS and/or perform some analysis after the data has been downloaded.

### 📖 Additional Details

See Step 2 from https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf

### Acceptance Criteria

**Given** the CSS archive
**When I perform** the steps described in the newly formed tutorial(s) for using the data
**Then I expect to** successfully perform the steps described for some analysis steps

**Comment by viviant100** [comment]
Tutorial of how to use CSS data:

- (1) Use fpack to unpack compressed FITZ image: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/fpackguide.pdf
- (2) Use Astropy: 
    - (a) https://docs.astropy.org/en/stable/io/fits/index.html
    - (b) https://docs.astropy.org/en/stable/io/fits/usage/cloud.html#fits-io-cloud
    - (c) https://docs.astropy.org/en/stable/generated/examples/io/plot_fits-image.html
- (3) Use PDS4 viewer: https://sbnwiki.astro.umd.edu/wiki/PDS4_Viewer
- (4) Use CATCH (Comet-Asteroid Telescopic Catalog Hub) service: : A moving-target search tool for large astronomical data sets, such as time-domain or near-Earth object surveys.
    - (a) https://catch.astro.umd.edu/about

**Comment by tloubrieu-jpl** [comment]
@jordanpadams , Vivian provided the information with the Open Data Registry submission. Do we want to make sure we also have that as part of the bundle label somewhere so that it is generically available to our users.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl this sounds like something that should go in the bundle readme.txt ? This is a file that can be referenced from the bundle.xml. Maybe we can ask if SBN wants to add that to the file?

**Comment by jordanpadams** [comment]
@viviant100 ☝️

**Comment by gxtchen** [comment]
@tloubrieu-jpl Which document contains the links provided by Vivian on Feb 6?

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen , I don't know but if we put ourself in the shoes of a user, I would expect to find it in the S3 bucket or on a web page findable with a google search like "Catalina Sky Survey data on PDS NASA".
The must as well be in the page describing the dataset on the ODR catalog https://registry.opendata.aws/, searching for "Catalina Sky Survey".

If one of these 3 resources is missing you can create a a ticket.
