### ISSUE TITLE
Submit an entry to the Registry of OpenData

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#92]
### 💡 Description

https://registry.opendata.aws

See Step 2 from https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf. 

### ⚔️ Parent Epic / Related Tickets

This was started here: https://github.com/NASA-PDS/planetary-data-cloud/pull/86

**Comment by viviant100** [comment]
Entry submitted to ODR and accepted on 1/25/24.  After it's accepted, the process of setting up a new AWS account with ODR begins.
