### ISSUE TITLE
Creating and link new AWS account for Open Data Registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#93]
### 💡 Description

See Step 4 from https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf.

Will need to work with MCP, NGAP, and Andy M. to determine what we need to do for this.

### ⚔️ Parent Epic / Related Tickets

- :unicorn: https://github.com/NASA-PDS/planetary-data-cloud/issues/71

**Comment by viviant100** [comment]
Submitted a MCP request (GSD-2889) to create a ODR AWS account that will be used exclusively for hosting CSS dataset.  Went over the details with MCP to create a new PDS-ODR Project with the account and provided details on CSS data so a dedicated s3 bucket can be created to serve css data in Open Data Registry.
