### ISSUE TITLE
Preparing and Upload CSS Data to AWS Open S3 Bucket

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/planetary-data-cloud#94]
### 💡 Description

See Step 5 from https://assets.opendata.aws/aws-onboarding-handbook-for-data-providers-en-US.pdf.

It says we should not proceed with this step until everything else has been completed, but I think we can start copying the data to our Nucleus Staging bucket for now, and then we can copy it over to the AWS Open Data bucket once we get here, since we can use the same region.

Note: Also includes cloud formation scripts for the S3 bucket and surrounding infra we create.

### ⚔️ Parent Epic / Related Tickets

Parent Epic:
- 🦄 https://github.com/NASA-PDS/planetary-data-cloud/issues/71

**Comment by viviant100** [comment]
Waiting on the following steps in order:
(1) Waiting on EMCC to accept the invite ODR sent on 2/5/24, and then 
(2) AWS has acknowledged that it is in their Payer Organization
(3) MCP finish up the inflation of the account.

**Comment by viviant100** [comment]
completed:

- created s3 bucket in odr
- uploaded sample css data in odr s3
- data is now in https://registry.opendata.aws/sbn-css/.
