### ISSUE TITLE
Create baseline IAM policies for AWS resources in MCP

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/planetary-data-cloud#95]
### 💡 Description

Create baseline IAM policies for AWS resources to be attached to new IAM roles 

1. Create a list of all AWS resources we use (EC2, S3, etc.)
2. Name these policies like pds_service-name_policy
3. Create and deploy baseline policy for each resource using Terraform
4. Get policies reviewed by SA team for least privilege access
5. Notify team to leverage these policies for new IAM roles

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl is developing a terraform module for this purpose.

**Comment by tloubrieu-jpl** [comment]
Some progress made and works for the development team. @sjoshi-jpl would like the feedback from the SA's on the organization of the modules (roles and policies)

**Comment by jordanpadams** [comment]
status: approved by SA team. to-be-moved to GitHub and reviewed for Thursday.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl is going to publish his terraform code for the SAs to review and deploy the roles in operations.

**Comment by tloubrieu-jpl** [comment]
@sagar created a ticket to create all the components needed.
