### ISSUE TITLE
Costing for Small Bodies - PostgreSQL Architecture in MCP

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/planetary-data-cloud#96]
### 💡 Description

Option 1: 
Cost high-availability PostgresSQL DB option (260 GB right now): https://docs.aws.amazon.com/prescriptive-guidance/latest/saas-multitenant-managed-postgresql/availability.html

Option 2:
	◦	Sync secondary DB using logical replication.
	◦	Develop new logical replication replicator app to export/import the appropriate subscriber states

Clients connecting into primary : ~20 clients
Download (Egress) : 500GB / month
Logical replication

Basic design : 
On-prem primary node --> Route53 failover into Cloud --> Multi AZDB PostgresSQL setup with logical replication

**Comment by jordanpadams** [comment]
Closing as wontfix. The MPC folks have done their thing, and since we have not heard back from them, we will close this for now
