### ISSUE TITLE
As a data user, I want to be able to view ODR S3 bucket with S3 browser app

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/planetary-data-cloud#99]
### Checked for duplicates

No - I haven't checked

### 💪 Motivation

...so that I can verify the data that was upload via DUM.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
@eddiesarevalo we will poke at this quickly at the beginning of next sprint.

**Comment by jordanpadams** [comment]
closing as duplicate to https://github.com/NASA-PDS/s3-browser/issues/15
